### ISSUE TITLE
Improve Converter Module (LA-ICP-MS)

### ISSUE THREAD

**Issue by ThorMark** [xmaptools/XMapTools_Developers#20]
- Automated zoom in does not work for primary standard or the sample
- Home button is buggy

**Comment by lanari** [comment]
The Zoom option has been fixed in commit https://github.com/xmaptools/XMapTools_Developers/commit/871856035ed740a850ce22be6beb8619d46f1834. 
This issue was only affecting the developer version of 4.4.
