### ISSUE TITLE
Error Message when opening XMapTools 4.3 (Jan 2024 version)

### ISSUE THREAD

**Issue by victoreguevara** [xmaptools/XMapTools_Developers#25]
I am using a MacBook Pro with the Apple M2 Pro chip on MacOS Sonoma 14.2. I followed all installation steps correctly (including deleting a previous version of XMapTools). However, when I try to open XMapTools, I get the following error message: 
![Screenshot 2024-06-26 at 2 17 34 PM](https://github.com/xmaptools/XMapTools_Developers/assets/144848195/ad2035a4-15fa-4669-8602-ef16127fbae4)

**Comment by lanari** [comment]
This looks like a permissions problem to me. Try typing the following command in a terminal: `chmod -R 755 /Applications/XMapTools/`

**Comment by victoreguevara** [comment]
That worked! Thank you Pierre.



Victor E. Guevara (he/him/his)
Assistant Professor
Department of Geology
Amherst College
302 Beneski
413-542-5708
Website <https://victoreguevara.weebly.com/>
